services:
  postgres:
    image: 'postgres:11.21-alpine3.17'
    environment:
      - 'POSTGRES_DB=my_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'

  minio:
    image: 'bitnami/minio:2023.9.30-debian-11-r0'
    ports:
      - "9000:9000"
      - "9001:9001"
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: root
#    command: server --console-address ":9001" /data
